load("@rules_python//python:defs.bzl", "py_test")
load("@pip//:requirements.bzl", "requirement")

py_test(
    name = "test_main",
    srcs = ["test_main.py", "conftest.py"],
    deps = [
        "//server:server",
        requirement("pytest"),
        requirement("pytest-mock"),
    ],
    main = "test_main.py",
    args = ["-v"],
)
